sonar.projectKey=BadCleanArch
sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo
sonar.pullrequest.cache.basepath=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo
sonar.sources=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.vs\\BadCleanArch\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.vs\\BadCleanArch\\v18\\DocumentLayout.json"

11111111-1111-1111-1111-111111111111.sonar.projectKey=BadCleanArch:11111111-1111-1111-1111-111111111111
11111111-1111-1111-1111-111111111111.sonar.projectName=Domain
11111111-1111-1111-1111-111111111111.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain
11111111-1111-1111-1111-111111111111.sonar.sourceEncoding=utf-8
11111111-1111-1111-1111-111111111111.sonar.tests=
11111111-1111-1111-1111-111111111111.sonar.sources=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\Entities\\Product.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\Interfaces\\IProductRepository.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\obj\\Domain.csproj.nuget.dgspec.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\obj\\project.assets.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\bin\\Debug\\net8.0\\Domain.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain\\obj\\Debug\\net8.0\\Domain.sourcelink.json"

11111111-1111-1111-1111-111111111111.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\0"
11111111-1111-1111-1111-111111111111.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\0\\Issues.json"
11111111-1111-1111-1111-111111111111.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\0\\Telemetry.json"

11111111-1111-1111-1111-111111111111.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod0
22222222-2222-2222-2222-222222222222.sonar.projectKey=BadCleanArch:22222222-2222-2222-2222-222222222222
22222222-2222-2222-2222-222222222222.sonar.projectName=Application
22222222-2222-2222-2222-222222222222.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application
22222222-2222-2222-2222-222222222222.sonar.sourceEncoding=utf-8
22222222-2222-2222-2222-222222222222.sonar.tests=
22222222-2222-2222-2222-222222222222.sonar.sources=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\obj\\Application.csproj.nuget.dgspec.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\obj\\project.assets.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\bin\\Debug\\net8.0\\Application.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\obj\\Debug\\net8.0\\Application.sourcelink.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\DTOs\\ProductDto.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\Interfaces\\IProductService.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\Services\\Calculator.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\Services\\ProductService.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application\\Validators\\ProductValidator.cs"

22222222-2222-2222-2222-222222222222.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\1"
22222222-2222-2222-2222-222222222222.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\1\\Issues.json"
22222222-2222-2222-2222-222222222222.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\1\\Telemetry.json"

22222222-2222-2222-2222-222222222222.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod1
33333333-3333-3333-3333-333333333333.sonar.projectKey=BadCleanArch:33333333-3333-3333-3333-333333333333
33333333-3333-3333-3333-333333333333.sonar.projectName=Infrastructure
33333333-3333-3333-3333-333333333333.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure
33333333-3333-3333-3333-333333333333.sonar.sourceEncoding=utf-8
33333333-3333-3333-3333-333333333333.sonar.tests=
33333333-3333-3333-3333-333333333333.sonar.sources=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure\\obj\\Infrastructure.csproj.nuget.dgspec.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure\\obj\\project.assets.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure\\bin\\Debug\\net8.0\\Infrastructure.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure\\obj\\Debug\\net8.0\\Infrastructure.sourcelink.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure\\Repositories\\InMemoryProductRepository.cs"

33333333-3333-3333-3333-333333333333.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\2"
33333333-3333-3333-3333-333333333333.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\2\\Issues.json"
33333333-3333-3333-3333-333333333333.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\2\\Telemetry.json"

33333333-3333-3333-3333-333333333333.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod2
44444444-4444-4444-4444-444444444444.sonar.projectKey=BadCleanArch:44444444-4444-4444-4444-444444444444
44444444-4444-4444-4444-444444444444.sonar.projectName=WebApi
44444444-4444-4444-4444-444444444444.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi
44444444-4444-4444-4444-444444444444.sonar.sourceEncoding=utf-8
44444444-4444-4444-4444-444444444444.sonar.tests=
44444444-4444-4444-4444-444444444444.sonar.sources=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\project.assets.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\WebApi.csproj.nuget.dgspec.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\bin\\Debug\\net10.0\\WebApi.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\bin\\Debug\\net10.0\\WebApi.runtimeconfig.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\bin\\Debug\\net10.0\\WebApi.staticwebassets.endpoints.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\WebApi.sourcelink.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\Controllers\\ProductsController.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\Program.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\WebApi.GlobalUsings.g.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\WebApi.AssemblyInfo.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi\\obj\\Debug\\net10.0\\WebApi.MvcApplicationPartsAssemblyInfo.cs"

44444444-4444-4444-4444-444444444444.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\3"
44444444-4444-4444-4444-444444444444.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\3\\Issues.json"
44444444-4444-4444-4444-444444444444.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\3\\Telemetry.json"

44444444-4444-4444-4444-444444444444.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod3
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.projectKey=BadCleanArch:6D9026B6-EE37-464E-BD30-A3CDA5E4D975
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.projectName=BadCleanArch.Tests
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.sourceEncoding=utf-8
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.sources=
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.tests=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\obj\\BadCleanArch.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\obj\\project.assets.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\Application.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\BadCleanArch.Tests.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\BadCleanArch.Tests.runtimeconfig.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\Domain.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\Infrastructure.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\WebApi.deps.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\WebApi.runtimeconfig.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\bin\\Debug\\net10.0\\WebApi.staticwebassets.endpoints.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\obj\\Debug\\net10.0\\BadCleanArch.Tests.sourcelink.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\obj\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\CalculatorTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\DomainTests\\ProductEntityTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\InfrastructureTests\\InMemoryProductRepositoryTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\IntegrationTests\\ProductsControllerIntegrationTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\IntegrationTests\\WebHostProductsTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\ProductsControllerTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\ProductServiceTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\ProductValidatorTests.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\UnitTest1.cs",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\coverage.opencover.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\012e0da2-49da-4c29-8d63-05924d13ccf5\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\10cecaff-75c0-43c5-a6d7-2dd5b59c2d5f\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\224e5976-2fe6-46b4-be74-920055f43446\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\71d297b5-640c-4fed-a72d-c763c073aafd\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\ba071740-5476-4e78-820b-7cb83bd5170d\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\d8cd3291-2523-4ea5-8277-449cee22ea53\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\e1e02e6d-cc2a-4207-8490-2a9e58f422a8\\coverage.cobertura.xml",\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests\\TestResults\\f79a704b-59e2-4c47-ae51-6a789abfd009\\coverage.cobertura.xml"

6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\4"
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\4\\Issues.json"
6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\4\\Telemetry.json"

6D9026B6-EE37-464E-BD30-A3CDA5E4D975.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod4
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.projectKey=BadCleanArch:E19D39E1-8BA7-469A-B9CD-F10524BDF447
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.projectName=Domain
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Domain
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.sourceEncoding=utf-8
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.tests=
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.sources=\


E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\5"
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\5\\Issues.json"
E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\5\\Telemetry.json"

E19D39E1-8BA7-469A-B9CD-F10524BDF447.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod5
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.projectKey=BadCleanArch:6714215C-8252-4DE9-AD8E-8B61BD4227ED
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.projectName=Application
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Application
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.sourceEncoding=utf-8
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.tests=
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.sources=\


6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\6"
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\6\\Issues.json"
6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\6\\Telemetry.json"

6714215C-8252-4DE9-AD8E-8B61BD4227ED.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod6
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.projectKey=BadCleanArch:B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.projectName=Infrastructure
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\Infrastructure
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.sourceEncoding=utf-8
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.tests=
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.sources=\


B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\7"
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\7\\Issues.json"
B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\7\\Telemetry.json"

B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod7
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.projectKey=BadCleanArch:FEAB9501-4FB4-4867-84F6-C60E3216E3DD
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.projectName=WebApi
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\src\\WebApi
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.sourceEncoding=utf-8
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.tests=
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.sources=\


FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\8"
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\8\\Issues.json"
FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\8\\Telemetry.json"

FEAB9501-4FB4-4867-84F6-C60E3216E3DD.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod8
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.projectKey=BadCleanArch:BB40D76B-0AB1-4391-AD62-D759CEA49D30
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.projectName=BadCleanArch.Tests
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.projectBaseDir=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\BadCleanArch.Tests
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.sourceEncoding=utf-8
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.sources=
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.tests=\


BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\9"
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\9\\Issues.json"
BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.cs.scanner.telemetry=\
"C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\9\\Telemetry.json"

BB40D76B-0AB1-4391-AD62-D759CEA49D30.sonar.working.directory=C:\\Users\\Windows\\Downloads\\ARQ_lim_nuevo\\.sonarqube\\out\\.sonar\\mod9
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=BadCleanArch.Tests/coverage.opencover.xml
sonar.exclusions=BadCleanArch.Tests/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=11111111-1111-1111-1111-111111111111,22222222-2222-2222-2222-222222222222,33333333-3333-3333-3333-333333333333,44444444-4444-4444-4444-444444444444,6D9026B6-EE37-464E-BD30-A3CDA5E4D975,E19D39E1-8BA7-469A-B9CD-F10524BDF447,6714215C-8252-4DE9-AD8E-8B61BD4227ED,B695218E-B2DB-4E7E-BFFE-6B29D9A26ACF,FEAB9501-4FB4-4867-84F6-C60E3216E3DD,BB40D76B-0AB1-4391-AD62-D759CEA49D30

